Creando el Primer Areglo con Numpay

In [2]:
import numpy  as np
arreglo=np.array([1,2,3,4,5])
print(arreglo)

[1 2 3 4 5]


Ejemplo de un Arreglo 1D (unidimensional)

In [3]:
import numpy  as np
arreglo_1d=np.array([1,2,3])
print(arreglo_1d)

[1 2 3]


Ejemplo de un  Arreglo 2D (bidimensional)

In [4]:
arreglo_2d=np.array([[1,2,3],[4,5,6]])
print(arreglo_2d)

[[1 2 3]
 [4 5 6]]


Ejemplos de  Arreglos con ceros o unos

In [5]:
ceros=np.zeros((2,3))
unos=np.ones ((3,2))
print("ceros:\n",ceros)
print("unos:\n",unos)

ceros:
 [[0. 0. 0.]
 [0. 0. 0.]]
unos:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


Ejemplo de Arreglos con rango

In [6]:
rango=np.arange(0,10,2)
print(rango)

[0 2 4 6 8]


Propiedades Basicas de los Arreglos
1. Dimensión y forma:

In [7]:
arreglo_2d = np.array([[1, 2], [3, 4], [5, 6]])

print("Dimensiones:", arreglo_2d.ndim) #2

print("Forma:", arreglo_2d.shape)

#(3, 2)

print("Tamaño:", arreglo_2d.size)

Dimensiones: 2
Forma: (3, 2)
Tamaño: 6


2. 2. Tipo de datos

In [8]:
print("Tipo de datos:", arreglo_2d.dtype)

Tipo de datos: int32


Operaciones básicas 
1. Operaciones elemento a elemento: 

In [27]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

print("Suma:", a + b)

print("Multiplicación:", a * b)

Suma: [5 7 9]
Multiplicación: [ 4 10 18]


2. Ejemplo de Operaciones con escalares: 

In [11]:
print("Multiplicar por 2:", a * 2)

Multiplicar por 2: [2 4 6]


Ejemplo de Funciones matemáticas: 

In [12]:
print("Raíz cuadrada:", np.sqrt(a))

print("Seno:", np.sin(a))


Raíz cuadrada: [1.         1.41421356 1.73205081]
Seno: [0.84147098 0.90929743 0.14112001]


Ejemplos de Indexación y segmentación (slicing)
1. Acceder a elementos: 

In [13]:
arreglo_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arreglo_2d[0, 1])

2


2. Segmentación: 

In [16]:
print(arreglo_2d[:, 1])
print(arreglo_2d [1, :])

[2 5]
[4 5 6]


Ejemplo de 3. Condiciones (indexación booleana): 

In [17]:
print(arreglo_2d[arreglo_2d > 3])

[4 5 6]


Ejemplos de Cambiar la forma de los arreglos
1. Redimensionar: 

In [20]:
arreglo = np.arange(6) # [012345]

nuevo = arreglo.reshape(2, 3)

print(nuevo)

[[0 1 2]
 [3 4 5]]


2. Ejemplo de Aplanar

In [21]:
plano = nuevo.flatten()

print(plano)

[0 1 2 3 4 5]


Ejemplos de Operaciones avanzadas
1. Producto punto: 

In [22]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6], [7, 8]])

print(np.dot(a, b))

[[19 22]
 [43 50]]


2. Transpuesta: 

In [23]:
print(a.T)

[[1 3]
 [2 4]]


3. Estadísticas: 

In [24]:
print("Suma:", np.sum(a))

print("Promedio:", np.mean(a))

print("Máximo:", np.max(a))

Suma: 10
Promedio: 2.5
Máximo: 4


Ejemplo de Generación de números aleatorios 
1. Números aleatorios:

In [25]:
aleatorios = np.random.rand(2, 3)
print(aleatorios)

[[0.44531496 0.52913424 0.28544762]
 [0.82679419 0.87908192 0.52916687]]


2. Enteros aleatorios: 

In [26]:
enteros = np.random.randint(1, 10, size=(2, 2))
print(enteros)

[[2 5]
 [9 5]]
