         Tutorial paso a páso

In [5]:
import numpy  as np
arreglo=np.array([1,2,3,4,5])
print(arreglo)

[1 2 3 4 5]


In [6]:
import numpy  as np
arreglo_1d=np.array([1,2,3])
print(arreglo_1d)

[1 2 3]


In [7]:
arreglo_2d=np.array([[1,2,3],[4,5,6]])
print(arreglo_2d)

[[1 2 3]
 [4 5 6]]


In [8]:
ceros=np.zeros((2,3))
unos=np.ones ((3,2))
print("ceros:\n",ceros)
print("unos:\n",unos)

ceros:
 [[0. 0. 0.]
 [0. 0. 0.]]
unos:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
rango=np.arange(0,10,2)
print(rango)


[0 2 4 6 8]


In [10]:
arreglo_2d = np.array([[1, 2], [3, 4], [5, 6]])

print("Dimensiones:", arreglo_2d.ndim) #

print("Forma:", arreglo_2d.shape)

print("Tamaño:", arreglo_2d.size)


Dimensiones: 2
Forma: (3, 2)
Tamaño: 6


In [11]:
print("Tipo de datos:", arreglo_2d.dtype)

Tipo de datos: int32


In [12]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

print("Suma:", a + b)

print("Multiplicación:", a * b)

Suma: [5 7 9]
Multiplicación: [ 4 10 18]


In [13]:
print("Multiplicar por 2:", a * 2) # [246]


Multiplicar por 2: [2 4 6]


In [14]:
print("Raíz cuadrada:", np.sqrt(a))

Raíz cuadrada: [1.         1.41421356 1.73205081]


In [15]:

print("Raíz cuadrada:", np.sqrt(a))

#2 [1. 1.414 1.732]

print("Seno:", np.sin(a))


Raíz cuadrada: [1.         1.41421356 1.73205081]
Seno: [0.84147098 0.90929743 0.14112001]


In [16]:
arreglo_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arreglo_2d[0, 1])


2


In [17]:
print(arreglo_2d[:, 1])
print(arreglo_2d [1, :])

[2 5]
[4 5 6]


In [18]:
print(arreglo_2d[arreglo_2d > 3])


[4 5 6]


In [23]:
arreglo =np.arange(6)

nuevo=arreglo.reshape(2, 3)

print(nuevo)


[[0 1 2]
 [3 4 5]]


In [25]:
plano =nuevo.flatten()

print(plano)

[0 1 2 3 4 5]


In [29]:
a= np.array([[1, 2], [3, 4]])

b=np.array([[5, 6], [7, 8]])

print(np.dot(a,b))

[[19 22]
 [43 50]]


In [31]:
print(a.T)

[[1 3]
 [2 4]]


In [40]:
print("Suma:", np.sum(a))
print("Promedio:", np.mean(a))
print("Maximo:",np.max(a))

Suma: 10
Promedio: 2.5
Maximo: 4


In [41]:
aleatorios=np.random.rand(2,3)
print(aleatorios)

[[0.10140341 0.08032657 0.86797474]
 [0.59944417 0.46128516 0.32691939]]


In [49]:
enteros = np.random.randint(1, 10, size=(2, 2))
print(enteros)

[[6 1]
 [1 1]]
